### ISSUE TITLE
Alternative Batteriedarstellung bei Zigbee-Geräten

### ISSUE THREAD

**Issue by JoAiWi** [iobroker-community-adapters/ioBroker.device-watcher#341]
Guten Morgen!

Ich hab letzte Woche vom Ali neue Temperatursensoren mit Display bekommen (Modell-Kennung ZTH05) und gestern in mein Zigbee-Netz integriert:
[https://de.aliexpress.com/item/1005006030373016.html](url)

Diese haben wieder eine "Neue Variante" in der Darstellung des Batteriezustandes: Anstatt die Batterie wie üblich in Prozenten darzustellen, heißt der Datenpunkt nun "battery_state" und meldet den Zustand in "High/Medium/Low" zurück.

![Zigbee](https://github.com/iobroker-community-adapters/ioBroker.device-watcher/assets/97600651/25ba4a3b-dc8e-439b-bd2a-5aea3a9875c4)

Lässt sich das irgendwie in die Batterie-Prüfung mit einbeziehen?

LG Johannes

**Comment by JoAiWi** [comment]
Übrigens: Ich finde es so cool, was du aus meiner Ursprungsidee vom "Zigbee-Watchdog" und meinem initialen Script gemacht hast. 👍
Ganz toll! Der Adapter hat mein Script recht unmittelbar abgelöst und seitdem hat sich da echt was getan.
Und das hätte ich so nie hinbekommen, da fehlt mir echt die Kragenweite! 😄

**Comment by ciddi89** [comment]
Moin @JoAiWi ,

du lebst ja doch noch. =D Leider habe ich ja nichts mehr von dir gehört. 
Danke erstmal für die Blumen ohne deine Idee und dein Skript am Anfang wäre es nicht soweit gekommen. Aber ein großer Dank geht auch an die Community mit ihren Ideen / Fehlermeldungen und Geduld diese zu beseitigen. Das Projekt war zuletzt echt eine Herzensangelegenheit. 
Ich muss dir aber leider sagen das ich die Fronten gewechselt habe und ich den Adapter der Dev-Community übergeben habe. Ich kann aber dieses Wochenende eben gucken das ich States Varianten mit Einpflege. Sind nur zwei-drei Änderungen. :)

Danke nochmal und ein schönes Wochenende

Christian
