### ISSUE TITLE
js-controller 6.0.1-alpha.0-20240529-9dbeeb628 Fehler im Log

### ISSUE THREAD

**Issue by Brainbug01** [iobroker-community-adapters/ioBroker.device-watcher#353]
Update auf den Alpha js-controller 6.0.1-alpha.0-20240529-9dbeeb628 bringt bei mir folgende Fehlermeldungen.
Adapter wurde gelöscht und neu installiert.

``
device-watcher.0 | 2024-05-30 11:20:10.370 | info | Found instances items on lists for timesettings: octoprint.1,octoprint.2
-- | -- | -- | --
device-watcher.0 | 2024-05-30 11:20:10.370 | info | Found instances items on blacklist for notifications: lg-thinq.0,discovery.0
device-watcher.0 | 2024-05-30 11:20:10.370 | info | Found instances items on blacklist for lists: lg-thinq.0,discovery.0
device-watcher.0 | 2024-05-30 11:20:10.369 | info | Number of selected adapters to monitor devices: 4. Loading data from: Fritzdect, FullybrowserV3, Shelly, Zigbee ...
device-watcher.0 | 2024-05-30 11:20:10.362 | info | starting. Version 2.12.1 in /opt/iobroker/node_modules/iobroker.device-watcher, node: v20.14.0, js-controller: 6.0.1-alpha.0-20240529-9dbeeb628
host.iobroker | 2024-05-30 11:20:09.491 | info | instance system.adapter.device-watcher.0 started with pid 3179
host.iobroker | 2024-05-30 11:20:06.338 | info | instance system.adapter.device-watcher.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
device-watcher.0 | 2024-05-30 11:20:06.299 | error | [getInstanceData] - Error: DB closed
device-watcher.0 | 2024-05-30 11:20:06.296 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.296 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.296 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.295 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.295 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.295 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.295 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.294 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.294 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.294 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.294 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.293 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.293 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.293 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.293 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.293 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.293 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.292 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.292 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.292 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.292 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.292 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.292 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.291 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.291 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.291 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.291 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.290 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.290 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.290 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.290 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.289 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.289 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.289 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.289 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.288 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.288 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.288 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.282 | error | Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.282 | error | Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:634:26) at Socket.emit (node:events:519:28) at Socket.emit (node:domain:488:12) at TCP.<anonymous> (node:net:338:12)
device-watcher.0 | 2024-05-30 11:20:06.282 | error | uncaught exception: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.281 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.280 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.279 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.278 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.278 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.278 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.278 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.278 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.277 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.277 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.276 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.276 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.276 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.275 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.274 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.273 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.272 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.272 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.272 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.272 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.272 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.271 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.271 | warn | redis get system.adapter.device-watcher.0.connected, error - Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.271 | warn | redis get system.adapter.device-watcher.0.connected, error - Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.265 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.264 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.264 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.264 | error | [getInstanceData] - TypeError: Cannot read properties of null (reading 'val')
device-watcher.0 | 2024-05-30 11:20:06.263 | warn | redis mget of 1 keys, err: DB closed
device-watcher.0 | 2024-05-30 11:20:06.263 | warn | redis mget of 1 keys, err: Connection is closed.
device-watcher.0 | 2024-05-30 11:20:06.224 | info | terminating
``

**Comment by mcm1957** [comment]
Sieht so aus als würden noch Aktinen ablaufen obwohl onUnload schon durchgelaufen ist,

Das Timerhandling wäre m.E. zu reviewen.

a) Es ist sicherzustellen, dass die Routine refreshData keinesfalls längere Zeit benötigt als das unload Timeout dauert.

b) Es wäre sicherzustellen, dass im Falle dass das unload während der Laufzeit der Routine refreshData auftritt nicht am Ende von refreshData das restart timeout erneut gestartet wird obwohl onUnload bereoits durchlaufen wurde.

Eventuell sollte man in onUnload einen "shutdownInProgress" Marker setzen der an geeigneten Stellen abgefragt wird udn die Aktionen beendet - zumindest aber das Starten eines neuen Timers blockiert.

c) Auf den ersten Blick ist nicht zu sehen wo die schedules Oprations beendet werden. Diese müssen jedenfalls bei onUnload sicher beendet werden - spätestens im Compact Mode können diese zu Problemen führen wenn sie nach dem Stoppen des Adapters noch (an-)laufen würden.

**Comment by foxriver76** [comment]
Kommt das mit den Fehlern im Log denn nur wenn der Adapter gestoppt wird? Das Log scheint ja von unten nach oben zu laufen, sprich der erste Logeintrag ist bereits Terminating?

**Comment by Brainbug01** [comment]
Ja ich hab einen Adapter restart ausgeführt. Ich bilde mir auch ein dass der device watcher das System auch träge macht.

**Comment by foxriver76** [comment]
Hm device-watcher ist so ein Adapter der je nach Konfig ein Haufen Einzelsubscribes macht, denke das sollte man mal bedenken zu optimieren.

**Comment by foxriver76** [comment]
Das Log oben schaut auch so aus als würde der ein Haufen State Updates in Folge bekommen die sich mit der Logik teilweise bis nach unload anstauen was zu den Meldungen führt.

**Comment by Brainbug01** [comment]
Und ich überwache meiner Meinung nach nicht mal viele Geräte. Fritzdect, FullybrowserV3, Shelly, Zigbee
99 insgesamt davon 66 mit Batterie.

**Comment by Apollon77** [comment]
My assumption is timing. The refresh method checks on startup as it seems if it is unloaded but not sure if also during refresh run. Somit could happen that the db is already gone but still refresh stuff is in progress. Especially when many states are read and such in a loop or such. Would require code check

**Comment by Apollon77** [comment]
So yes there are several loops in that refesh that all await state gets and such. So if such a refresh run takes in sum more then 500ms (which can easiely happen on low performance systems or with a higher number of monitored devices/states) then this has an issue.

Options ar: Add into all these refresh loops checks "if unloaded return" or add an higher close timeout. Second option can still get problematic on slow systems with high numner of states because it is unknown how long a refresh takes usually.

**Comment by Brainbug01** [comment]
Mein System:

Betriebssystem: linux
Architektur: x64
CPUs: 4
Modell: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
RAM: 10 GB

lxc unter Proxmox, CPU Auslastung laut Proxmox bei 3%

**Comment by mcm1957** [comment]
> So yes there are several loops in that refesh that all await state gets and such. So if such a refresh run takes in sum more then 500ms (which can easiely happen on low performance systems or with a higher number of monitored devices/states) then this has an issue.
> 

@Apollon77 
Would await block unload? I think that unload code, especially onUnload callback will run in parallel with the refreshData code blocked at several awaits. Increasing the shutdown timer will not help in this case as a successful return from onUnload will cancel the timer an close the db.

Or is this knowledge incorrect?

**Comment by Apollon77** [comment]
In fact a successful callback from unload adds 200ms or such and then kills DB, right. SO as said ... ideally we would need to add unload checks in all "loops" in the refresh logic that this is cancelled when unload happened

**Comment by Brainbug01** [comment]
Ich bin auf js-controller 6.0.4 und Fehler vom device-watcher sind keine vorhanden? Am device-watcher wurde ja nicht verändert? Liegt es an den Änderungen am js-controller das keine Fehler mehr da sind?

**Comment by Brainbug01** [comment]
Seit einigen Wochen keine Probleme mehr.

**Comment by mcm1957** [comment]
thanks for feedback
